# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u0413\u040c\u0413\xa0\u0413\xa7\u0413\u045e\u0413\xa0\u0413\xad\u0413\u0401\u0413\u0490')),
                ('description', models.TextField(verbose_name=b'descr')),
                ('content', models.TextField(verbose_name=b'cont')),
                ('price', models.FloatField(db_index=True, verbose_name=b'prc')),
                ('price_acc', models.FloatField(blank=True, null=True, verbose_name='price22')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name=b'instock')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name=b'feat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name=b'categ')),
            ],
            options={
                'verbose_name': 'verb',
                'verbose_name_plural': 'plural',
            },
        ),
    ]
